### ISSUE TITLE
The context has not gained a legitimation due to missing access rights.

### ISSUE THREAD

**Issue by kaisermario** [trocotronic/weconnect#11]
Hello @trocotronic , 

first of all I was very happy that I've found your repository. 
Thanks for your work!

Unfortunately I get the following error: 

```
[13/12/2022 14:36:28] [API::CRITICAL] Raising error msg: Error 403: [VSR.security.9007] The context has not gained a legitimation due to missing access rights.
Traceback (most recent call last):
  File "/Users/kama/git/div/weconnect/example.py", line 46, in <module>
    vsr = vwc.get_vsr(vin)
  File "/Users/kama/git/div/weconnect/NativeAPI.py", line 502, in get_vsr
    r = self.__command('/bs/vsr/v1/{brand}/{country}/vehicles/'+vin+'/status', dashboard=self.__get_fal_url(vin), scope=self.__oauth['sc2:fal'], accept=self.__accept_mbb)
  File "/Users/kama/git/div/weconnect/NativeAPI.py", line 171, in __command
    r = self.__get_url(dashboard+command, json=post, post=data, headers=headers)
  File "/Users/kama/git/div/weconnect/NativeAPI.py", line 130, in __get_url
    raise UrlError(r.status_code, msg, r)
NativeAPI.UrlError: Error 403: [VSR.security.9007] The context has not gained a legitimation due to missing access rights.
```
so it's working until line 45 of your example.py
do you have an idea?

Best regards,
Mario

**Comment by trocotronic** [comment]
Remove files `weconnectAPI.session` and `weconnectAPI.access` and try again.

**Comment by trocotronic** [comment]
No news.
