### ISSUE TITLE
Logging in not possible since Feb 13, 2023

### ISSUE THREAD

**Issue by videopix** [trocotronic/weconnect#13]
Since a few days logging in with the python script is not possible anymore. The VW app still works fine though.
This is what I get when I run example.py: 

[17/02/2023 12:25:14] [API::WARNING] Session file not found
[17/02/2023 12:25:14] [API::WARNING] Access file not found
[17/02/2023 12:25:14] [API::WARNING] Forcing login
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    vwc.login()
  File "NativeAPI.py", line 277, in login
    return self.__force_login()
  File "NativeAPI.py", line 361, in __force_login
    self.__identities = get_url_params(r.history[-1].url)
  File "NativeAPI.py", line 59, in get_url_params
    params[para[0]] = unquote_plus(para[1])
IndexError: list index out of range

Any idea?

**Comment by trocotronic** [comment]
VW sent another round of consents. Everytime is a huge mess. Fortunately it appears unlikely twice a year. 

Can you give a try to latest commit? If it does not work, go to `https://www.myvolkswagen.net/`, log in and accept/decline the consents. Once done, the API should work.

**Comment by videopix** [comment]
Thanks for the quick reply.
Using the latest version did not fix it. But after logging in and consenting the cookie popup it works again.
Great!

**Comment by RoadRunnner** [comment]
Thank you for this hint.
After log in my access to E-Golf and ID3 are working fine.
ID3 is using different python script, but this solution was working there too.

**Comment by denimmonkey** [comment]
Logged in and consented but still facing the same issues. Anything else that can I try?
Also with this package is it possible to control charging?

**Comment by trocotronic** [comment]
Still happening?

**Comment by RoadRunnner** [comment]
Yes, since 15.11 2023 I am not able to get data from vehicle. In Germany WeConnect app is not longer supported by VW. Is it still working on your site?Gesendet von Outlook für Android
