### ISSUE TITLE
401 error since update of 27th of November

### ISSUE THREAD

**Issue by enzioardesch** [trocotronic/weconnect#22]
Since the update on the 27th of November one error persists:

[10/12/2023 17:30:00] [API::WARNING] Session file not found
[10/12/2023 17:30:00] [API::WARNING] Access file not found
[10/12/2023 17:30:00] [API::WARNING] Forcing login

[10/12/2023 17:30:02] [API::CRITICAL] Raising error msg: Error: status code 401
Traceback (most recent call last):
  File "/home/deb117581/kmlogpython/example.py", line 15, in <module>
    vwc.login()
  File "/home/deb117581/kmlogpython/NativeAPI.py", line 281, in login
    return self.__force_login()
  File "/home/deb117581/kmlogpython/NativeAPI.py", line 426, in __force_login
    r = self.__get_url('https://www.volkswagen.es/app/authproxy/vw-es/user', headers=headers)
  File "/home/deb117581/kmlogpython/NativeAPI.py", line 130, in __get_url
    raise UrlError(r.status_code, msg, r)
NativeAPI.UrlError: Error: status code 401

**Comment by EckhardM** [comment]
I confirm this issue - same for me!

**Comment by enzioardesch** [comment]
> I confirm this issue - same for me!

Have you managed to find a fix? I have tried tillsteinbach's script, but it sometimes takes up to 30 seconds to fetch the data...

**Comment by EckhardM** [comment]
> > I confirm this issue - same for me!
> 
> Have you managed to find a fix? I have tried tillsteinbach's script, but it sometimes takes up to 30 seconds to fetch the data...

I moved to https://github.com/tillsteinbach/WeConnect-python

**Comment by enzioardesch** [comment]
> > > I confirm this issue - same for me!
> > 
> > 
> > Have you managed to find a fix? I have tried tillsteinbach's script, but it sometimes takes up to 30 seconds to fetch the data...
> 
> I moved to https://github.com/tillsteinbach/WeConnect-python

What's your experience with fetching time? I have only quickly tried it, and not deployed it with that yet.

**Comment by EckhardM** [comment]
> > > > I confirm this issue - same for me!
> > > 
> > > 
> > > Have you managed to find a fix? I have tried tillsteinbach's script, but it sometimes takes up to 30 seconds to fetch the data...
> > 
> > 
> > I moved to https://github.com/tillsteinbach/WeConnect-python
> 
> What's your experience with fetching time? I have only quickly tried it, and not deployed it with that yet.

Yes, it takes a few seconds but i run it only every five minutes. For me it's okay.

**Comment by busunrise** [comment]
I have got the same problem. I have tried Till Steinbach's solution and was able to print(vehicle) with the allVehicles.py example. 
Login time is only a few seconds. My question is how can I retrieve specific data e.g. odo meter etc. Is there an JSON API available? It's a pity that the description is very superficial.

**Comment by EckhardM** [comment]
> I have got the same problem. I have tried Till Steinbach's solution and was able to print(vehicle) with the allVehicles.py example. Login time is only a few seconds. My question is how can I retrieve specific data e.g. odo meter etc. Is there an JSON API available? It's a pity that the description is very superficial.

If you asked for Till Steinbach's solution let's discuss it there: https://github.com/tillsteinbach/

**Comment by busunrise** [comment]
Ok, your are right!
